REPLACE INTO `#prefix#_bbsmilies` (`smilies_id`, `code`, `smile_url`, `emoticon`) VALUES
(1, ':D', 'icon_biggrin.gif', 'Very Happy'),
(2, ':-D', 'icon_biggrin.gif', 'Very Happy'),
(3, ':grin:', 'icon_biggrin.gif', 'Very Happy'),
(4, ':)', 'icon_smile.gif', 'Smile'),
(5, ':-)', 'icon_smile.gif', 'Smile'),
(6, ':smile:', 'icon_smile.gif', 'Smile'),
(7, ':(', 'icon_sad.gif', 'Sad'),
(8, ':-(', 'icon_sad.gif', 'Sad'),
(9, ':sad:', 'icon_sad.gif', 'Sad'),
(10, ':o', 'icon_surprised.gif', 'Surprised'),
(11, ':-o', 'icon_surprised.gif', 'Surprised'),
(12, ':eek:', 'icon_surprised.gif', 'Surprised'),
(13, '8O', 'icon_eek.gif', 'Shocked'),
(14, '8-O', 'icon_eek.gif', 'Shocked'),
(15, ':shock:', 'icon_eek.gif', 'Shocked'),
(16, ':?', 'icon_confused.gif', 'Confused'),
(17, ':-?', 'icon_confused.gif', 'Confused'),
(18, ':???:', 'icon_confused.gif', 'Confused'),
(19, '8)', 'icon_cool.gif', 'Cool'),
(20, '8-)', 'icon_cool.gif', 'Cool'),
(21, ':cool:', 'icon_cool.gif', 'Cool'),
(22, ':lol:', 'icon_lol.gif', 'Laughing'),
(23, ':x', 'icon_mad.gif', 'Mad'),
(24, ':-x', 'icon_mad.gif', 'Mad'),
(25, ':mad:', 'icon_mad.gif', 'Mad'),
(26, ':P', 'icon_razz.gif', 'Razz'),
(27, ':-P', 'icon_razz.gif', 'Razz'),
(28, ':razz:', 'icon_razz.gif', 'Razz'),
(29, ':oops:', 'icon_redface.gif', 'Embarassed'),
(30, ':cry:', 'icon_cry.gif', 'Crying or Very sad'),
(31, ':evil:', 'icon_evil.gif', 'Evil or Very Mad'),
(32, ':twisted:', 'icon_twisted.gif', 'Twisted Evil'),
(33, ':roll:', 'icon_rolleyes.gif', 'Rolling Eyes'),
(34, ':wink:', 'icon_wink.gif', 'Wink'),
(35, ';)', 'icon_wink.gif', 'Wink'),
(36, ';-)', 'icon_wink.gif', 'Wink'),
(37, ':!:', 'icon_exclaim.gif', 'Exclamation'),
(38, ':?:', 'icon_question.gif', 'Question'),
(39, ':idea:', 'icon_idea.gif', 'Idea'),
(40, ':arrow:', 'icon_arrow.gif', 'Arrow'),
(41, ':|', 'icon_neutral.gif', 'Neutral'),
(42, ':-|', 'icon_neutral.gif', 'Neutral'),
(43, ':neutral:', 'icon_neutral.gif', 'Neutral'),
(44, ':mrgreen:', 'icon_mrgreen.gif', 'Mr. Green');
