CREATE TABLE `nuke_users` (
  `user_id` int(11) NOT NULL,
  `user_type` tinyint(2) NOT NULL DEFAULT 0,
  `nuke_group_id` mediumint(8) UNSIGNED NOT NULL DEFAULT 3,
  `group_id` mediumint(8) UNSIGNED NOT NULL DEFAULT 3,
  `user_permissions` mediumtext NOT NULL DEFAULT '',
  `user_perm_from` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `user_ip` varchar(40) NOT NULL DEFAULT '',
  `user_regdate` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `username` varchar(255) NOT NULL DEFAULT '',
  `username_clean` varchar(255) NOT NULL DEFAULT '',
  `user_email` varchar(255) NOT NULL DEFAULT '',
  `user_email_hash` bigint(20) NOT NULL DEFAULT 0,
  `user_birthday` varchar(10) NOT NULL DEFAULT '',

  `user_website` varchar(255) NOT NULL DEFAULT '',
  `user_occ` text NOT NULL DEFAULT '',
  `user_avatar` varchar(255) NOT NULL DEFAULT '',
  `user_interests` text NOT NULL DEFAULT '',
  `user_actkey` varchar(32) NOT NULL DEFAULT '',

  `user_password` varchar(40) NOT NULL DEFAULT '',
  `user_form_salt` varchar(32) NOT NULL DEFAULT '',
  `user_arcade_pm` tinyint(1) NOT NULL DEFAULT 1,
  `games_per_page` smallint(5) UNSIGNED NOT NULL DEFAULT 0,
  `games_sort_dir` varchar(1) NOT NULL DEFAULT 'a',
  `games_sort_order` varchar(1) NOT NULL DEFAULT 'n',
  `user_gender` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `user_arcade_permissions` mediumtext NOT NULL DEFAULT '',
  `user_arcade_perm_from` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `user_reminder_inactive` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_reminder_zero_poster` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_reminder_inactive_still` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_reminder_not_logged_in` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_flag` varchar(2) NOT NULL DEFAULT '',
  `user_passchg` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_pass_convert` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,

  `user_session_time` int(11) NOT NULL DEFAULT 0,

  `user_lastvisit` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_lastmark` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_lastpost_time` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_lastpage` varchar(200) NOT NULL DEFAULT '',
  `user_last_confirm_key` varchar(10) NOT NULL DEFAULT '',
  `user_last_search` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_warnings` tinyint(4) NOT NULL DEFAULT 0,
  `user_last_warning` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_login_attempts` tinyint(4) NOT NULL DEFAULT 0,
  `user_inactive_reason` tinyint(2) NOT NULL DEFAULT 0,
  `user_inactive_time` int(11) UNSIGNED NOT NULL DEFAULT 0,

  `user_timezone` decimal(5,2) NOT NULL DEFAULT 0.00,
  `user_dst` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
 
  `user_style` mediumint(8) UNSIGNED NOT NULL DEFAULT 0,
  `user_lang` varchar(30) NOT NULL DEFAULT '',

  `user_dateformat` varchar(30) NOT NULL DEFAULT 'd M Y H:i',
  `user_new_privmsg` int(5) NOT NULL DEFAULT 0,
  `user_unread_privmsg` int(5) NOT NULL DEFAULT 0,
  `user_last_privmsg` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_message_rules` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `user_full_folder` int(11) NOT NULL DEFAULT -3,

  `user_emailtime` int(11) UNSIGNED NOT NULL DEFAULT 0,
  `user_topic_show_days` smallint(4) UNSIGNED NOT NULL DEFAULT 0,
  `user_topic_sortby_type` varchar(1) NOT NULL DEFAULT 't',
  `user_topic_sortby_dir` varchar(1) NOT NULL DEFAULT 'd',
  `user_post_show_days` smallint(4) UNSIGNED NOT NULL DEFAULT 0,
  `user_post_sortby_type` varchar(1) NOT NULL DEFAULT 't',

  `user_allow_pm` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `user_allow_viewonline` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `user_allow_viewemail` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `user_allow_massemail` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `user_options` int(11) UNSIGNED NOT NULL DEFAULT 895,
  `user_notify` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,

  `user_notify_pm` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `user_notify_type` tinyint(4) NOT NULL DEFAULT 0,

  `user_avatar_width` smallint(4) UNSIGNED NOT NULL DEFAULT 0,
  `user_avatar_height` smallint(4) UNSIGNED NOT NULL DEFAULT 0,

  `user_sig_bbcode_bitfield` varchar(255) NOT NULL DEFAULT '',
  `user_from` varchar(100) NOT NULL DEFAULT '',
  `user_icq` varchar(15) NOT NULL DEFAULT '',
  `user_aim` varchar(255) NOT NULL DEFAULT '',
  `user_yim` varchar(255) NOT NULL DEFAULT '',
  `user_msnm` varchar(255) NOT NULL DEFAULT '',
  `user_jabber` varchar(255) NOT NULL DEFAULT '',
  `user_newpasswd` varchar(40) DEFAULT NULL,

) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf